"use client";

import React from "react";
import { ExportSummaryData, generateMonthlySummaryPDF } from "@/src/app/utils/exportUtils";

type Props = {
  data: ExportSummaryData;
  promptedBy?: string;
  onClose: () => void;
};

export default function SummaryPreview({ data, promptedBy, onClose }: Props) {
  function downloadPDF() {
    const pdf = generateMonthlySummaryPDF(data);
    pdf.save(`summary_${data.dateRange.start}_to_${data.dateRange.end}.pdf`);
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={onClose}></div>

      <div className="relative w-full max-w-2xl bg-slate-900 rounded-lg shadow-xl border border-slate-700 overflow-hidden">
        <div className="p-4 border-b border-slate-700 flex items-center justify-between">
          <div>
            <h3 className="text-lg font-semibold text-white">Summary Preview</h3>
            <p className="text-sm text-slate-400 mt-1">Preview of the export before downloading</p>
          </div>
          <div className="text-sm text-slate-300">Generated by: <span className="font-medium text-white">{promptedBy || "Current User"}</span></div>
        </div>

        <div className="p-4">
          <div className="bg-white/5 rounded-md overflow-hidden border border-slate-700">
            <div className="grid grid-cols-2">
              <div className="px-4 py-3 bg-blue-100/60">
                <span className="text-sm font-medium text-slate-800">Metric</span>
              </div>
              <div className="px-4 py-3 bg-blue-100/60 border-l border-slate-200/20">
                <span className="text-sm font-medium text-slate-800">Value</span>
              </div>
            </div>

            <div className="divide-y divide-slate-700">
              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Period</div>
                <div className="text-sm text-white">{data.dateRange.start} — {data.dateRange.end}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Total Revenue</div>
                <div className="text-sm text-white">₱{data.totalRevenue.toFixed(2)}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Total Orders</div>
                <div className="text-sm text-white">{data.totalOrders}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Average Order Value</div>
                <div className="text-sm text-white">₱{data.avgOrderValue.toFixed(2)}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">New Customers</div>
                <div className="text-sm text-white">{data.newCustomers}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Returning Customers</div>
                <div className="text-sm text-white">{data.returningCustomers}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Pick-up Only</div>
                <div className="text-sm text-white">{data.fulfillmentBreakdown.pickupOnly}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Delivery Only</div>
                <div className="text-sm text-white">{data.fulfillmentBreakdown.deliveryOnly}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">Pick-up & Delivery</div>
                <div className="text-sm text-white">{data.fulfillmentBreakdown.both}</div>
              </div>

              <div className="grid grid-cols-2 px-4 py-3">
                <div className="text-sm text-slate-300">In-store</div>
                <div className="text-sm text-white">{data.fulfillmentBreakdown.inStore}</div>
              </div>
            </div>
          </div>
        </div>

        <div className="p-4 flex items-center justify-end gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-md text-sm"
          >
            Close
          </button>

          <button
            onClick={downloadPDF}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm shadow-md"
            title="Download PDF"
          >
            Download PDF
          </button>
        </div>
      </div>
    </div>
  );
}
